OrdererOrgs:
  - Name: Orderer
    Domain: supplychain.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer1
        SANS:
          - localhost
          - 127.0.0.1
      - Hostname: orderer2
        SANS:
          - localhost
          - 127.0.0.1
      - Hostname: orderer3
        SANS:
          - localhost
          - 127.0.0.1
